FROM python:3.12-slim
WORKDIR /app

COPY requirements.lock /requirements.lock
RUN pip install --no-cache-dir -r /requirements.lock

COPY utils /app/utils

EXPOSE 8501
CMD ["streamlit", "run", "utils/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
