name: news_dbt
version: "1.0.0"
config-version: 2
profile: news_pipeline

model-paths: ["models"]

models:
  news_dbt:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
