version: 2

models:
  - name: mart_daily_news_stats
    columns:
      - name: published_date
        data_tests:
          - not_null
          - unique
      - name: news_count
        data_tests:
          - not_null

  - name: mart_validation_quality
    columns:
      - name: run_id
        data_tests:
          - not_null
          - unique
      - name: total_rows
        data_tests:
          - not_null
      - name: valid_rows
        data_tests:
          - not_null
      - name: quarantine_rows
        data_tests:
          - not_null
      - name: valid_rate
        data_tests:
          - not_null
      - name: quarantine_rate
        data_tests:
          - not_null
      - name: overall_status
        data_tests:
          - not_null
